### ISSUE TITLE
How to cast the desktop?

### ISSUE THREAD

**Issue by All3xJ** [Rafostar/playercast#16]
I was able to cast a video from my ChromeOS tablet (in which I installed playercast inside the Linux crostini VM, and since it's a VM I needed to also do a port forwarding before casting). But what about casting my chromebook tablet desktop? Is there a way to do that? To what I understand, I am only able to share a video...

**Comment by Rafostar** [comment]
As mentioned in features: "Supports casting videos, music, pictures and web links", so desktop casting is not currently supported. Casting host desktop from within VM running on it would probably not be possible anyway.
