### ISSUE TITLE
is this supposed to work with ChromeCast?

### ISSUE THREAD

**Issue by airtonix** [Rafostar/playercast#7]
tried it and expected to see the `playercast --name pennyroyal` to show up on the list of casting targets in my android phone...

but nope. nothing.

**Comment by Rafostar** [comment]
No, this is not using Chromecast protocol (its encrypted so I cant use it). This is for casting to media player like `mpv` or `vlc` and controlling playback remotely. This one here works as both desktop server and client. If you would like to cast from Android device, one would have to to make an Android server/controller application (certainly possible to do).

Right now I am busy working on a new GNOME media player (for Linux), so I personally will not be making it anytime soon. Maybe after its done and added to list of supported media players here, but it still has a long way to go before I can call it stable.
